config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  
  # ショップ用
  # URL /shops/sign_in ...
  devise_for :shops,skip: [:passwords], controllers: {
    registrations: "shop/registrations",
    sessions: 'shop/sessions'
  }
  namespace :shop do
    get 'top' => 'homes#top', as: 'top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end
  
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  
  # 在庫数が0以上であることを確認
  validates :stock, numericality: { greater_than_or_equal_to: 0 }
  # カテゴリが重複しないことを確認
  validates :category, uniqueness: true
  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :description, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/shop/confirmations_controller.rb
# frozen_string_literal: true

class Shop::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/shop/homes_controller.rb
class Shop::HomesController < ApplicationController
  def top
  end
end

app/controllers/shop/items_controller.rb
class Shop::ItemsController < ApplicationController
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to shop_item_path(@item), notice: '商品が正常に登録されました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :category, :image, :stock)
  end
  
end

app/controllers/shop/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Shop::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/shop/passwords_controller.rb
# frozen_string_literal: true

class Shop::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/shop/registrations_controller.rb
# frozen_string_literal: true

class Shop::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/shop/sessions_controller.rb
# frozen_string_literal: true

class Shop::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  

  protected
  
  def after_sign_in_path_for(resource)
    shop_top_path
  end
  
  def after_sign_out_path_for(resource)
    new_shop_session_path
  end

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :encrypted_password) }
  end

  
end

app/controllers/shop/unlocks_controller.rb
# frozen_string_literal: true

class Shop::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/shop/items/index.html.erb
<h1>商品一覧</h1>

<%= link_to '商品登録', new_shop_item_path %>

<ul>
  <% @items.each do |item| %>
    <li>
      <%= link_to item.name, shop_item_path(item.id) %>
    </li>
  <% end %>
</ul>

app/views/shop/items/new.html.erb
<h1>新規商品登録</h1>

<%= form_with model: [:shop, @item], local: true do |form| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :商品名 %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :商品説明 %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :価格 %><br>
    <%= form.number_field :price, min: 0 %>
  </div>

  <div>
    <%= form.label :カテゴリー %><br>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :商品画像 %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :在庫数 %><br>
    <%= form.number_field :stock, min: 0 %>
  </div>

  <div>
    <%= form.submit '登録' %>
  </div>
<% end %>

<%= link_to '戻る', shop_items_path %>

app/views/shop/items/show.html.erb
<h1><%= @item.name %></h1>

<p><strong>説明:</strong> <%= @item.description %></p>
<p><strong>価格:</strong> <%= @item.price %></p>
<p><strong>カテゴリ:</strong> <%= @item.category %></p>
<p><strong>在庫数:</strong> <%= @item.stock %></p>
<p><strong>画像:</strong> <%= image_tag @item.image if @item.image.present? %></p>

<%= link_to '編集', edit_shop_item_path(@item) %> |
<%= link_to '戻る', shop_items_path %>