config/routes.rb
Rails.application.routes.draw do
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "customer/registrations",
    sessions: 'customer/sessions'
  }
  
  # ショップ用
  # URL /shops/sign_in ...
  devise_for :shops,skip: [:passwords], controllers: {
    registrations: "shop/registrations",
    sessions: 'shop/sessions'
  }
  namespace :shop do
    get 'top' => 'homes#top', as: 'top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end
  
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

end

app/views/layouts/_header.html.erb
<header>
  <nav>
    <% if customer_signed_in? %>
      <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %>
    <% elsif shop_signed_in? %>
      <%= link_to 'ログアウト', destroy_shop_session_path, method: :delete %>
    <% elsif admin_signed_in? %>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <main>
    <%= yield %>
    </main>
    <%= render 'layouts/footer'%>
  </body>
</html>